blank_issues_enabled: false
contact_links:
  - name: â“ Q&A
    url: https://github.com/brenocq/implot3d/discussions/categories/q-a
    about: Have any questions or need help? Ask here!
  - name: ğŸ“¸ Gallery
    url: https://github.com/brenocq/implot3d/discussions/3
    about: Share screenshots, GIFs, or videos of your 3D visualizations
