name: ğŸ MacOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    name: ğŸ MacOS
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          cd example
          cmake -B build -DCMAKE_CXX_FLAGS="-Wall -Werror"
          cmake --build build
